// Faithful Rust reimplementation of kissat 4.0.4 (solver 13).
// main.rs mirrors main.c + (eventually) application.c.

pub mod analyze;
pub mod ands;
pub mod application;
pub mod arena;
pub mod assign;
pub mod averages;
pub mod backbone;
pub mod backtrack;
pub mod bump;
pub mod classify;
pub mod clause;
pub mod compact;
pub mod decide;
pub mod deduce;
pub mod definition;
pub mod dense;
pub mod collect;
pub mod colors;
pub mod config;
pub mod eliminate;
pub mod equivalences;
pub mod error;
pub mod extend;
pub mod fastel;
pub mod file;
pub mod flags;
pub mod forward;
pub mod format;
pub mod frames;
pub mod gates;
pub mod heap;
pub mod ifthenelse;
pub mod import;
pub mod inline;
pub mod inlinequeue;
pub mod internal;
pub mod kimits;
pub mod kitten;
pub mod krite;
pub mod learn;
pub mod literal;
pub mod lucky;
pub mod minimize;
pub mod mode;
pub mod options;
pub mod parse;
pub mod phases;
pub mod preprocess;
pub mod print;
pub mod probe;
pub mod profile;
pub mod promote;
pub mod proof;
pub mod propbeyond;
pub mod propdense;
pub mod propinitially;
pub mod proprobe;
pub mod propsearch;
pub mod queue;
pub mod random;
pub mod reduce;
pub mod reference;
pub mod reluctant;
pub mod reorder;
pub mod rephase;
pub mod report;
pub mod resize;
pub mod resolve;
pub mod resources;
pub mod restart;
pub mod search;
pub mod shrink;
pub mod smooth;
pub mod sort;
pub mod statistics;
pub mod strengthen;
pub mod stubs;
pub mod substitute;
pub mod sweep;
pub mod congruence;
pub mod factor;
pub mod terminate;
pub mod tiers;
pub mod trail;
pub mod transitive;
pub mod utilities;
pub mod value;
pub mod vector;
pub mod vivify;
pub mod walk;
pub mod warmup;
pub mod watch;
pub mod weaken;
pub mod witness;

fn main() {
    // main.c's body (solver setup, signal handling, run, teardown) lives in
    // application::application; exit with its code (0/1/10/20).
    let args: Vec<String> = std::env::args().collect();
    let res = application::application(args);
    std::process::exit(res);
}
